; Classroom Word Builder — Computational Thinking
[Puzzle]
title=Python Programming Lab-Introduction
font_size=36
rows=10
columns=30
letter_view=scrambled
word_preview_seconds=3
show_words_to_find=false
ask_questions=false

[Words]
word1=HARDWARE
word2=SOFTWARE
word3=INPUT
word4=OUTPUT
word5=MEMORY
word6=RAM
word7=ROM
word8=CPU
word9=KEYBOARD
word10=MOUSE
word11=MONITOR
word12=PRINTER
word13=SCANNER
word14=SPEAKER
word15=MICROPHONE
word16=PENDRIVE
word17=COMPUTER
word18=PROCESSOR
word19=DESKTOP
word20=LAPTOP



[Questions]

