; Classroom Word Hunt — Python Set 2
[Puzzle]
title=Python Programming Word Hunt
rows=9
columns=17
font_size=24
directions=horizontal,vertical,diagonal
allow_reverse=false
allow_overlap=true
hints=true
show_words_to_find=true
ask_questions=true

[Words]
word1=ENGINEERING
word2=PROBLEM
word3=COMPUTATIONAL
word4=PROBLEMSOLVING
word5=ALGORITHM
word6=CODING
word7=TESTING
word8=DEBUGGING
word9=ERROR
word10=FLOWCHART
word11=PSEUDOCODE

[Questions]
ENGINEERING.enabled=true
ENGINEERING.question=Define Engineering?
ENGINEERING.answer=Engineering is the field of applying science and mathematics to solve real-world problems and create useful solutions

PROBLEM.enabled=true
PROBLEM.question=Define Real-World Engineering problems?
PROBLEM.answer=In engineering, a problem is the need or gap that an engineer must identify, define clearly, and solve within given limits such as time, cost, and materials

COMPUTATIONAL.enabled=true
COMPUTATIONAL.question=Define Computational Thinking?
COMPUTATIONAL.answer=Computational thinking is the thought processes involved in formulating a problem and expressing its solution(s) in such a way that a computer—human or machine—can effectively carry out

PROBLEMSOLVING.enabled=true
PROBLEMSOLVING.question=What are steps involved in Problem Solving Framework?
PROBLEMSOLVING.answer=1. Analyse the problem, 2. Develop the Algorithm, 3. Coding, 4. Testing and Debugging

ALGORITHM.enabled=true
ALGORITHM.question=Define Algorithm?
ALGORITHM.answer=Algorithm is a step-by-step solution to the problem, or the rules to follow to solve the problem

CODING.enabled=true
CODING.question=What happens in a coding phase of the problem solving framework?
CODING.answer=Finalized algorithm is converted into the format which can be understood by the computer to generate the desired solution using a high level programming language

TESTING.enabled=true
TESTING.question=What is software testing?
TESTING.answer=Software testing is the process of running a program with different inputs and checking whether it produces the expected results and meets the requirements

DEBUGGING.enabled=true
DEBUGGING.question=What is software debugging?
DEBUGGING.answer=Debugging is the process of finding, identifying, and fixing errors in a program

ERROR.enabled=true
ERROR.question=What is a software error and what are its common types?
ERROR.answer=A software error is a human mistake made during software development. common types: 1. Syntax error, 2. Runtime error, 3.Logical error

FLOWCHART.enabled=true
FLOWCHART.question=What is a flowchart?
FLOWCHART.answer=A flowchart is a visual representation of an algorithm. It is made up of boxes, diamonds and other shapes, connected by arrows

PSEUDOCODE.enabled=true
PSEUDOCODE.question=Pseudocode is a non-formal language that helps programmers to write algorithm.No specific standard exists for writing a pseudocode. True or False?
PSEUDOCODE.answer=True
 








