; Classroom Word Hunt — Python Set 2
[Puzzle]
title=Python Programming Word Hunt-1
rows=9
columns=17
font_size=24
directions=horizontal,vertical,diagonal
allow_reverse=true
allow_overlap=true
hints=true
show_words_to_find=false
ask_questions=true

[Words]
word1=ENGINEERING
word2=PROBLEM
word3=COMPUTATIONAL
word4=DECOMPOSITION
word5=ABSTRACTION
word6=PATTERN
word7=ALGORITHM
word8=PYTHON
word9=PROGRAMMING


[Questions]
ENGINEERING.enabled=true
ENGINEERING.question=Define Engineering?
ENGINEERING.answer=Engineering is the field of applying science and mathematics to solve real-world problems and create useful solutions

PROBLEM.enabled=true
PROBLEM.question=Define Real-World Engineering problems?
PROBLEM.answer=In engineering, a problem is the need or gap that an engineer must identify, define clearly, and solve within given limits such as time, cost, and materials

COMPUTATIONAL.enabled=true
COMPUTATIONAL.question=What is Computational Thinking?
COMPUTATIONAL.answer=Computational thinking is the thought processes involved in formulating a problem and expressing its solution(s) in such a way that a computer—human or machine—can effectively carry out

DECOMPOSITION.enabled=true
DECOMPOSITION.question=What is Decomposition(in the context of Computational Thinking)?
DECOMPOSITION.answer=Decomposition Breaking down a complex problem or system into smaller, more manageable parts 

ABSTRACTION.enabled=true
ABSTRACTION.question=What is Abstraction(in the context of Computational Thinking)?
ABSTRACTION.answer=Focusing on the important information only, ignoring irrelevant detail

PATTERN.enabled=true
PATTERN.question=What is Pattern Recoginition(in the context of Computational Thinking)?
PATTERN.answer= Looking for similarities among and within problems

ALGORITHM.enabled=true
ALGORITHM.question=What is Algorithm Design(in the context of Computational Thinking)?
ALGORITHM.answer=Developing a step-by-step solution to the problem, or the rules to follow to solve the problem

PYTHON.enabled=true
PYTHON.question=Explain in simple words about Python Programming Language?
PYTHON.answer=Python is a programming language used to write instructions for computers in an easy-to-read way

PROGRAMMING.enabled=true
PROGRAMMING.question=Define Software Programming?
PROGRAMMING.answer=Programming is the process of writing instructions in a language a computer can understand so it can perform a task or solve a problem









